spring:
  datasource:
    driverClassName: org.h2.Driver
    username: sa
    password: sa
    max-wait: '10000'
    tomcat:
      max-idle: '5'
      max-active: '10'
      min-idle: '3'
    url: jdbc:h2:file:~/db/myOrg.db;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;
  h2:
    console:
      path: /h2
      enabled: 'true'
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: 'true'
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: 'true'
logging:
  level:
    org:
      hibernate: TRACE
    root: DEBUG
